### ISSUE TITLE
alicebot 0.8.1 版本运行报错

### ISSUE THREAD

**Issue by ziyii01** [AliceBotProject/alicebot#92]
系统: windows 11
py版本: 3.10.11
alicebot 版本：0.8.1
（alicebot 0.7.1 版本正常运行无报错）

报错详情：
每次接收到消息就会报错. 
```
2023-10-01 07:44:17.739 | INFO     | alicebot.adapter.cqhttp:reverse_ws_connection_hook:88 - WebSocket connected!
2023-10-01 07:44:17.742 | INFO     | alicebot.adapter.cqhttp:handle_cqhttp_event:195 - WebSocket connection from CQHTTP Bot xxx accepted!
Error handling request
Traceback (most recent call last):
  File "c:\ziyii\bot\bot\venv\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "c:\ziyii\bot\bot\venv\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "c:\ziyii\bot\bot\venv\lib\site-packages\alicebot\adapter\utils.py", line 250, in handle_reverse_ws_response
    await self.handle_websocket()
  File "c:\ziyii\bot\bot\venv\lib\site-packages\alicebot\adapter\utils.py", line 271, in handle_websocket
    await self.handle_websocket_msg(msg)
  File "c:\ziyii\bot\bot\venv\lib\site-packages\alicebot\adapter\cqhttp\__init__.py", line 122, in handle_websocket_msg
    await self.handle_cqhttp_event(msg_dict)
  File "c:\ziyii\bot\bot\venv\lib\site-packages\alicebot\adapter\cqhttp\__init__.py", line 187, in handle_cqhttp_event
    cqhttp_event = event_class(adapter=self, **msg)
  File "c:\ziyii\bot\bot\venv\lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for GroupMessageEvent
message.is-instance[CQHTTPMessage]
  Input should be an instance of CQHTTPMessage [type=is_instance_of, input_value='xxx', input_type=str]
    For further information visit https://errors.pydantic.dev/2.4/v/is_instance_of
message.function-after[CQHTTPMessage(), list[CQHTTPMessageSegment]]
  Input should be a valid list [type=list_type, input_value='xxx', input_type=str]
    For further information visit https://errors.pydantic.dev/2.4/v/list_type
2023-10-01 07:44:27.957 | INFO     | alicebot.adapter.cqhttp:reverse_ws_connection_hook:88 - WebSocket connected!
2023-10-01 07:44:27.958 | INFO     | alicebot.adapter.cqhttp:handle_cqhttp_event:195 - WebSocket connection from CQHTTP Bot xxx accepted!
```

**Comment by st1020** [comment]
这可能是因为你没有将协议端的上报数据类型设置为 array。
例如对于 CQHTTP：
```yaml
message:
  # 上报数据类型
  post-format: array
```
